### ISSUE TITLE
How to handle OS signals

### ISSUE THREAD

**Issue by neophyt3** [yagehu/sample-fx-app#1]
I was thinking to handle OS signals for graceful shutdown but It seems difficult to incorporate in this example. 
Would it be like handling os signals outside of fx app and then calling stop with the Timeout context?

**Comment by yagehu** [comment]
Hi! Yes you can set up signal handling in an `fx.Invoke` block. I just added this code to demonstrate it:

https://github.com/yagehu/sample-fx-app/blob/0247f8811999a116dee43989966e8b1acc01aa43/internal/routes/register.go#L42-L58

**Comment by neophyt3** [comment]
@yagehu  awesome, this helps. Thanks
